import { create } from 'zustand'
import type { ScheduleItem, ScheduleViewMode, ScheduleItemType, ScheduleStatus } from './types'

const STORAGE_KEY = 'sagara-schedule-items'

const INITIAL_SCHEDULES: ScheduleItem[] = [
  {
    id: 'sched-001',
    type: 'RECURRING_JOB',
    title: 'Daily Marketing Briefing',
    description: 'Autonomous scan of social mentions, traffic conversions, and lead metrics.',
    startAt: '2026-09-10T09:00:00.000Z',
    endAt: '2026-09-10T09:45:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: {
      frequency: 'WEEKDAYS',
      interval: 1,
      cronExpression: '0 9 * * 1-5',
    },
    agentId: 'marketing',
    profileId: 'marketing',
    priority: 'HIGH',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    notes: 'Generated by Sagara Marketing Profile blueprint',
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'sched-002',
    type: 'TASK',
    title: 'Follow-up Qualified Leads',
    description: 'High-intent lead qualification review and CRM pipeline synchronization.',
    startAt: '2026-09-10T11:30:00.000Z',
    endAt: '2026-09-10T12:30:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: { frequency: 'NONE' },
    agentId: 'business',
    profileId: 'business',
    priority: 'HIGH',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    createdAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'sched-003',
    type: 'MAINTENANCE',
    title: 'Infrastructure & Gateway Health Review',
    description: 'Hermes runtime heartbeat audit, process memory verification, and telemetry flush.',
    startAt: '2026-09-10T15:00:00.000Z',
    endAt: '2026-09-10T16:00:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: {
      frequency: 'DAILY',
      interval: 1,
    },
    agentId: 'it_support',
    profileId: 'it_support',
    priority: 'MEDIUM',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    createdAt: '2026-09-03T11:00:00.000Z',
  },
  {
    id: 'sched-004',
    type: 'REMINDER',
    title: 'Governance Gate Expiration Warning',
    description: 'Pending shell execution approval expires in 30 minutes.',
    startAt: '2026-09-10T16:30:00.000Z',
    endAt: '2026-09-10T17:00:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: { frequency: 'NONE' },
    priority: 'CRITICAL',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    createdAt: '2026-09-04T12:00:00.000Z',
  },
  {
    id: 'sched-005',
    type: 'CONTENT',
    title: 'Weekly Tech Editorial Dispatch',
    description: 'Weekly tech roundup generation and multiplatform broadcast validation.',
    startAt: '2026-09-11T10:00:00.000Z',
    endAt: '2026-09-11T11:30:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: {
      frequency: 'WEEKLY',
      interval: 1,
      byWeekDays: [5], // Friday
    },
    agentId: 'marketing',
    profileId: 'marketing',
    priority: 'MEDIUM',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    createdAt: '2026-09-05T09:00:00.000Z',
  },
  {
    id: 'sched-006',
    type: 'EVENT',
    title: 'Team Sync & Agent Delegation Retrospective',
    description: 'Cross-functional review of agent delegations and operational costs.',
    startAt: '2026-09-12T14:00:00.000Z',
    endAt: '2026-09-12T15:00:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: { frequency: 'NONE' },
    priority: 'LOW',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    createdAt: '2026-09-05T14:00:00.000Z',
  },
  {
    id: 'sched-007',
    type: 'TASK',
    title: 'Advisory Conflict Test Task',
    description: 'Overlaps with Daily Marketing Briefing to verify advisory conflict banner.',
    startAt: '2026-09-10T09:15:00.000Z',
    endAt: '2026-09-10T10:15:00.000Z',
    timezone: 'Asia/Jakarta',
    recurrence: { frequency: 'NONE' },
    agentId: 'marketing',
    profileId: 'marketing',
    priority: 'MEDIUM',
    status: 'SCHEDULED',
    source: 'PROTOTYPE',
    createdAt: '2026-09-06T10:00:00.000Z',
  },
]

export { detectScheduleConflicts } from './schedule-utils'
export type { ScheduleConflict } from './schedule-utils'

function loadInitialSchedules(): ScheduleItem[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed
      }
    }
  } catch {
    // Fallback to initial
  }
  return INITIAL_SCHEDULES
}

function saveSchedules(items: ScheduleItem[]) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items))
  } catch {
    // Ignore quota errors in sandbox
  }
}

interface ScheduleState {
  items: ScheduleItem[];
  viewMode: ScheduleViewMode;
  selectedDate: string; // ISO format (e.g. "2026-09-10")
  searchQuery: string;
  typeFilter: ScheduleItemType | 'ALL';
  statusFilter: ScheduleStatus | 'ALL';
  agentFilter: string | 'ALL';

  setViewMode: (viewMode: ScheduleViewMode) => void;
  setSelectedDate: (date: string) => void;
  setSearchQuery: (query: string) => void;
  setTypeFilter: (type: ScheduleItemType | 'ALL') => void;
  setStatusFilter: (status: ScheduleStatus | 'ALL') => void;
  setAgentFilter: (agent: string | 'ALL') => void;

  addSchedule: (item: Omit<ScheduleItem, 'id' | 'createdAt' | 'source'>) => ScheduleItem;
  updateSchedule: (id: string, patch: Partial<ScheduleItem>) => void;
  deleteSchedule: (id: string) => void;
  duplicateSchedule: (id: string) => ScheduleItem | null;
  resetToDefaults: () => void;
}

export const useScheduleStore = create<ScheduleState>((set, get) => ({
  items: loadInitialSchedules(),
  viewMode: 'month',
  selectedDate: '2026-09-10',
  searchQuery: '',
  typeFilter: 'ALL',
  statusFilter: 'ALL',
  agentFilter: 'ALL',

  setViewMode: (viewMode) => set({ viewMode }),
  setSelectedDate: (selectedDate) => set({ selectedDate }),
  setSearchQuery: (searchQuery) => set({ searchQuery }),
  setTypeFilter: (typeFilter) => set({ typeFilter }),
  setStatusFilter: (statusFilter) => set({ statusFilter }),
  setAgentFilter: (agentFilter) => set({ agentFilter }),

  addSchedule: (data) => {
    const newItem: ScheduleItem = {
      ...data,
      id: `sched-${Date.now().toString(36)}`,
      source: 'PROTOTYPE',
      createdAt: new Date().toISOString(),
    }
    const updated = [newItem, ...get().items]
    saveSchedules(updated)
    set({ items: updated })
    return newItem
  },

  updateSchedule: (id, patch) => {
    const updated = get().items.map((it) => (it.id === id ? { ...it, ...patch } : it))
    saveSchedules(updated)
    set({ items: updated })
  },

  deleteSchedule: (id) => {
    const updated = get().items.filter((it) => it.id !== id)
    saveSchedules(updated)
    set({ items: updated })
  },

  duplicateSchedule: (id) => {
    const original = get().items.find((it) => it.id === id)
    if (!original) return null
    const cloned: ScheduleItem = {
      ...original,
      id: `sched-${Date.now().toString(36)}`,
      title: `${original.title} (Copy)`,
      createdAt: new Date().toISOString(),
      source: 'PROTOTYPE',
    }
    const updated = [cloned, ...get().items]
    saveSchedules(updated)
    set({ items: updated })
    return cloned
  },

  resetToDefaults: () => {
    saveSchedules(INITIAL_SCHEDULES)
    set({ items: INITIAL_SCHEDULES })
  },
}))
